# Generated by Django 5.2 on 2025-04-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_detallepedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cupon',
        ),
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
