# Generated by Django 5.2 on 2025-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_permiso_rol_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
